New package: snake
termux/game-packages pull request #61
Opened 2020-09-07 13:40 UTC by TipzTeam

I've made a little snake game for Termux.

2020-09-07 13:42 UTC, kcubeterm commented
I think you should use more suitable description .

2020-09-07 13:45 UTC, TipzTeam commented
> I think you should use more suitable description .

Let's see what the reviewers say.

2020-09-07 14:30 UTC, Grimler91 commented
Hi, I like the updated description, very accurate!

Seems the original project is here: https://github.com/gogakoreli/snake/

There are some problems: 
* The original code does not have a license, [basically meaning that it cannot be used for anything](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license). I see that you have licensed it as MIT, have you been in contact with @gogakoreli and been told that this is okay?
* The included stdc++.h file is licensed under GPL-3, meaning that the package should be dual licensed, however:
* The included stdc++.h from glibc is not needed. It seems that it is only needed for things like std::cout and std::endl, these are defined in iostream in termux so you can just do `#include <iostream>` to solve it

So, sorry, but unless the original code is licensed correctly we cannot add it to our repositories

2020-09-07 14:32 UTC, TipzTeam commented
> Hi, I like the updated description, very accurate!
> 
> Seems the original project is here: https://github.com/gogakoreli/snake/
> 
> There are some problems:
> 
> * The original code does not have a license, [basically meaning that it cannot be used for anything](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license). I see that you have licensed it as MIT, have you been in contact with @gogakoreli and been told that this is okay?
> * The included stdc++.h file is licensed under GPL-3, meaning that the package should be dual licensed, however:
> * The included stdc++.h from glibc is not needed. It seems that it is only needed for things like std::cout and std::endl, these are defined in iostream in termux so you can just do `#include <iostream>` to solve it
> 
> So, sorry, but unless the original code is licensed correctly we cannot add it to our repositories

I will work on those issues and I will come back asap

2020-09-07 14:46 UTC, TipzTeam commented
- [ ] MIT license issue
- [x] Remove stdc++

Fun fact, this works with clang and g++

2020-09-07 14:47 UTC, TipzTeam commented
Also @Grimler91, can I not license this project and be done with it?

2020-09-07 14:55 UTC, TipzTeam commented
Actually, I think I can license it in Public domain @Grimler91

2020-09-07 15:04 UTC, Grimler91 commented
> Actually, I think I can license it in Public domain @Grimler91

It is only public domain if that is stated in the project, or if the original author says so, see https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license.

2020-09-07 19:51 UTC, xeffyr requested changes
Fix build.sh, with resolving license issue pointed by @Grimler91.

2020-09-07 19:51 UTC, xeffyr commented on packages/snake/build.sh
> +TERMUX_PKG_SRCURL=https://github.com/TipzTeam/snake-cpp-termux/archive/${TERMUX_PKG_VERSION}.tar.gz
Forks shouldn't be used unless there is a good reason, e.g. original owner transferred project's ownership.

If source requires some changes to get working in Termux, this should be done through patches placed in directory where build.sh is located.

If project doesn't specify a version (https://github.com/gogakoreli/snake/ doesn't specify it), then you should use a date of latest commit in format YYYY.MM.DD and in source URL a git commit hash should be used.

2020-09-07 19:51 UTC, xeffyr commented on packages/snake/build.sh
> +TERMUX_PKG_BUILD_DEPENDS="clang, make"
Remove these two from build depends. Packages are cross-compiled by NDK and clang/make are useless here.

2020-09-07 23:45 UTC, TipzTeam commented
The original porject is licensed in MIT according to the project owner.

2020-09-08 00:16 UTC, TipzTeam commented
It's failing because there's no license file.

2020-09-08 01:12 UTC, xeffyr commented
> The original project is licensed in MIT according to the project owner.

Where's that info?

2020-09-08 01:49 UTC, TipzTeam commented
> > The original project is licensed in MIT according to the project owner.
> 
> Where's that info?

here: https://twitter.com/team_tipz/status/1302978693862625283

2020-09-08 09:29 UTC, TipzTeam commented
Thanks!

2020-09-08 09:31 UTC, xeffyr approved these changes

2020-09-08 09:31 UTC, merged

2020-09-08 09:31 UTC, TipzTeam commented
Yay

2020-09-08 10:02 UTC, TipzTeam commented
@xeffyr tested in termux, not opening.

2020-09-08 10:03 UTC, TipzTeam commented
In build:
"aarch64-linux-android-strip: Unable to recognise the format of the input file `./bin/snake'"

2020-09-08 10:03 UTC, TipzTeam commented
it was working with this one: c85ff0e02154c5babb4dbdba0413741a8b420c77